title: "My Awesome Blog"
description: "A place for awesome content"
theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# theme: jekyll-theme-tactile
# theme: jekyll-theme-hyde
author: "Your Name"
